-- Endbosse für Boss-Serien. Weitere Namen können pro Instanz einfach ergänzt werden.
-- Aliasnamen sind erlaubt, falls WoW Forever einen Boss anders meldet als die Bossliste.
GambleEndBosses = {
    ["Ragefire Chasm"] = { "Taragaman the Hungerer" },
    ["Wailing Caverns"] = { "Mutanus the Devourer" },
    ["The Deadmines"] = { "Edwin VanCleef" },
    ["Shadowfang Keep"] = { "Archmage Arugal" },
    ["The Stockade"] = { "Bazil Thredd" },
    ["Blackfathom Deeps"] = { "Aku'mai" },
    ["Gnomeregan"] = { "Mekgineer Thermaplugg" },
    ["Razorfen Kraul"] = { "Charlga Razorflank" },
    ["Scarlet Monastery Graveyard"] = { "Bloodmage Thalnos" },
    ["Scarlet Monastery Library"] = { "Arcanist Doan" },
    ["Scarlet Monastery Armory"] = { "Herod" },
    ["Scarlet Monastery Cathedral"] = { "High Inquisitor Whitemane", "Scarlet Commander Mograine" },
    ["Razorfen Downs"] = { "Amnennar the Coldbringer" },
    ["Uldaman"] = { "Archaedas" },
    ["Zul'Farrak"] = { "Chief Ukorz Sandscalp" },
    ["Maraudon"] = { "Princess Theradras" },
    ["Sunken Temple"] = { "Shade of Eranikus" },
    ["Blackrock Depths"] = { "Emperor Dagran Thaurissan" },
    ["Lower Blackrock Spire"] = { "Overlord Wyrmthalak" },
    ["Upper Blackrock Spire"] = { "General Drakkisath" },
    ["Dire Maul East"] = { "Alzzin the Wildshaper" },
    ["Dire Maul West"] = { "Prince Tortheldrin" },
    ["Dire Maul North"] = { "King Gordok" },
    ["Stratholme"] = { "Baron Rivendare", "Balnazzar" },
    ["Scholomance"] = { "Darkmaster Gandling" },
    ["Molten Core"] = { "Ragnaros" },
    ["Onyxia's Lair"] = { "Onyxia" },
    ["Zul'Gurub"] = { "Hakkar" },
    ["Blackwing Lair"] = { "Nefarian" },
    ["Ruins of Ahn'Qiraj"] = { "Ossirian the Unscarred" },
    ["Temple of Ahn'Qiraj"] = { "C'Thun" },
    ["Naxxramas"] = { "Kel'Thuzad" },
}
